pipeline {
    agent {
    docker {
        image 'python:3.10'
        args '-u root:root'
    }
    }
    environment {
        VENV_DIR = '.venv'
    }

    stages {
        stage('Checkout Code') {
            steps {
                git branch: 'main', url: 'https://github.com/hananmyy/alx-backend-python.git'
            }
        }

        stage('Set Up Python Environment') {
            steps {
                sh '''
                    python3 -m venv $VENV_DIR
                    source $VENV_DIR/bin/activate
                    pip install --upgrade pip
                    pip install -r messaging_app/requirements.txt
                '''
            }
        }

        stage('Run Tests') {
            steps {
                sh '''
                    source $VENV_DIR/bin/activate
                    pytest messaging_app/tests --junitxml=report.xml
                '''
            }
        }

        stage('Archive Test Results') {
            steps {
                junit 'report.xml'
            }
        }
    }
}