#!/bin/bash

# Deploy both versions
kubectl apply -f blue_deployment.yaml
kubectl apply -f green_deployment.yaml
kubectl apply -f kubeservice.yaml

# Check logs of the green deployment
GREEN_POD=$(kubectl get pods -l app=messaging-app-green -o jsonpath="{.items[0].metadata.name}")
kubectl logs $GREEN_POD